name: Test, Build and Publish a next version

on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - next
    types:
      - 'closed'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: NPM install, lint, build, test and release
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm ci
          npm run lint
          # npm run test:ci
          npm run build
          npm run test:lib:ci
          npm run build:lib
          npx semantic-release --debug
